version: '3'

services:
  jenkins:
    build: ./jenkins #use customized Jenkins image
    ports:
      - "8080:8080"
    volumes:
      - $HOME:/home
      - jenkins_data:/var/jenkins_home
    environment:
      - SONARQUBE_HOST_URL="http://sonarqube:9000"
      - SONARQUBE_LOGIN="" #replace with generated key from Sonarqube
    networks:
      - devnet

  sonarqube:
    image: sonarqube:6.7.5-alpine
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - devnet

volumes:
  jenkins_data:

networks:
  devnet:
    driver: bridge