version: '3'

services:
  jenkins:
    build: ./jenkins
    ports:
      - "8080:8080"
    volumes:
      - $HOME:/home
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SONARQUBE_HOST_URL="http://sonarqube:9000"
      - SONARQUBE_LOGIN="764349cc48a36088856f95356dc6611e3f3372e8"
    networks:
      - devnet

  sonarqube:
    image: sonarqube:6.7.5-alpine
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - devnet

volumes:
  jenkins_data:

networks:
  devnet:
    driver: bridge