pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('QA') {
            steps {
                sh "mvn -P sonar verify -DskipTests -Dsonar.host.url=${env.SONARQUBE_HOST_URL} -Dsonar.login=${env.SONARQUBE_LOGIN}"
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
